### ISSUE TITLE
Error running in development mode

### ISSUE THREAD

**Issue by alexandro-tegra** [johannesh2/textfieldformatter#24]
From version 4.1.1 I'm facing the following Error
 
```
java.lang.IllegalStateException: Running project in development mode with no access to folder 'C:\Users\Johannes\github\textfieldformatter\target\checkout'.
Build project in production mode instead, see https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html
	at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyFolderExists(DeploymentConfigurationFactory.java:397) ~[flow-server-2.1.3.jar:2.1.3]
	at com.vaadin.flow.server.DeploymentConfigurationFactory.readBuildInfo(DeploymentConfigurationFactory.java:201) ~[flow-server-2.1.3.jar:2.1.3]
	at com.vaadin.flow.server.DeploymentConfigurationFactory.createInitParameters(DeploymentConfigurationFactory.java:172) ~[flow-server-2.1.3.jar:2.1.3]
	at com.vaadin.flow.server.DeploymentConfigurationFactory.createPropertyDeploymentConfiguration(DeploymentConfigurationFactory.java:133) ~[flow-server-2.1.3.jar:2.1.3]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$SpringStubServletConfig.createDeploymentConfiguration(VaadinServletContextInitializer.java:782) ~[vaadin-spring-12.1.2.jar:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:312) ~[vaadin-spring-12.1.2.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4680) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5143) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [na:na]
...

```

**Comment by johanneshayry** [comment]
OK sorry about that I have probably made a mistake with the release. Let me release another one.

**Comment by johanneshayry** [comment]
Which version of Vaadin are you using. The bug in Flow was fixed a while ago https://github.com/vaadin/flow/issues/6616

I can do a release to get rid of the build-info.json file

**Comment by johanneshayry** [comment]
Please try 4.1.4
